# Generated by Django 4.2.11 on 2024-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=60)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('item_value', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PublicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=50)),
                ('item_value', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
